volumes:
  pgdata:

services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sample
    volumes:
      - pgdata:/var/lib/postgresql
    command: postgres -c wal_level=logical
    ports:
      - 5432:5432

  debezium-server-postgres:
    image: quay.io/debezium/server
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials/service-account.json
    ports:
      - "8888:8080"
    volumes:
      - ./service-account.json:/tmp/credentials/service-account.json
      - ./config:/debezium/config
