CREATE TABLE
    USERS (id UUID PRIMARY KEY, NAME TEXT);

CREATE TABLE
    comments (id UUID PRIMARY KEY, content TEXT);

CREATE TABLE
    posts (id UUID PRIMARY KEY, content TEXT);

CREATE TABLE
    heartbeat (id UUID PRIMARY KEY);

CREATE TABLE
    debezium_signal (
        id VARCHAR(42) PRIMARY KEY,
        TYPE VARCHAR(32) NOT NULL,
        DATA VARCHAR(2048) NULL
    );